version: "3.8"

services:
  php:
    # image: php-docker-template-php
    container_name: mmrfc-php-logger
    build:
      context: ./docker
      dockerfile: Dockerfile
      args:
        PHP_VERSION: 7.4.33
        XDEBUG_VERSION: 3.1.2
        COMPOSER_VERSION: 2.1.14
    volumes:
      - type: bind
        source: ./
        target: /var/www/html
        # Override `/usr/local/etc/php-fpm.d/zz-docker.conf` configuration in
        # Docker container.
        # See: https://github.com/docker-library/php/issues/241
    ulimits:
      memlock:
        soft: -1
        hard: -1