sonar.projectKey=madeiramadeirabr_lib-php-logger
sonar.organization=madeiramadeirabr
sonar.php.coverage.reportPaths=coverage.xml
sonar.coverage.exclusions=**/tests/**
sonar.exclusions=.git/**,tmp/**,dist/**,libs/**,node/**,.vscode/**,bin/**,coverage/**,test/**,build/**,vendor/**,.idea/**