name: changelog
on:
  push:
    branches:
      - production

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        id: release
        uses: madeiramadeirabr/action-generate-release@0.1.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
  changelog:
    runs-on: ubuntu-latest
    name: 'Changelog'
    needs: release
    steps:
      - name: Checkout        
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: update package.json
        uses: madeiramadeirabr/action-generate-changelog@0.1.2
        with:
            github-token: ${{ secrets.GITHUB_TOKEN }}