name: unit test
on:
  pull_request:
    branches:
      - production


jobs:
  run:    
    runs-on: production
    strategy:
      matrix:
        php-versions: ['7.1', '7.2', '7.3', '8.0', '8.1']
    name: PHP ${{ matrix.php-versions }} Test on production
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
    - name: Install dependencies
      run: |
        composer install \
          --no-progress  \
          --optimize-autoloader
    - name: Run tests
      run: ./vendor/bin/phpunit